use `rphone`;

drop table if exists `parts_of_speech`;
create table `parts_of_speech`(
	`id` int primary key,
	`speechpart` varchar(64));
	
insert into `parts_of_speech` values
(1,'noun'),
(2,'verb'),
(3,'adjective');

create table if not exists `long_words` (
	`id` int primary key auto_increment,
	`word` varchar(64),
	`pattern` varchar(64),
	`speechpart` tinyint,
	`sound` varchar(64));
	
insert into `long_words` (`word`, `pattern`, `speechpart`, `stress_count`) values
('university', '_u|ni^ver|si|ty', 1, 2),
('characteristic', '_char|ac|te^ris|tic', 3, 2),
('constitution', '_con|sti^tu|tion', 1, 2),
('information', '_in|for^ma|tion', 1, 2),
('multiplication', '_mul|ti|pli^ca|tion', 1, 2),
('punctuation', '_punc|tu^a|tion', 1, 2),
('conversation', '_con|ver^sa|tion', 1, 2),
('investigation', '|in_ves|ti^ga|tion', 1, 2),
('continuation', '|con_tin|u^a|tion', 1, 2),
('interpretation', '|in_ter|pre^ta|tion', 1, 2),
('accomodation', '|ac_com|o^da|tion', 1, 2),
('consideration', '|con_sid|e^ra|tion', 1, 2),
('responsibility', '|re_spon|si^bil|i|ty', 1, 2),
('familiarity', '|fa_mil|i^ar|i|ty', 1, 2),
('incredibility', '|in_cred|i^bil|i|ty', 1, 2),
('availability', '|a_vai|la^bil|i|ty', 1, 2),
('personification', '|per_son|i|fi^ca|tion', 1, 2),
('communication', '|com_mu|ni^ca|tion', 1, 2),
('education', '_ed|u^ca|tion', 1, 2),
('imagination', '|i_mag|i^na|tion', 1, 2),
('reservation', '_res|er^va|tion', 1, 2),
('appreciation', '|ap_pre|ci^a|tion', 1, 2),
('contradiction', '_con|tra^dic|tion', 1, 2),
('economics', '_e|co^nom|ics', 1, 2),
('hostility', '_hos^til|i|ty', 1, 2),
('identity', '_i^den|ti|ty', 1, 2),
('academic', '_ac|a^dem|ic', 3, 2),
('capitalistic', '_cap|i|ta^lis|tic', 3, 2),
('experimental', '|ex_per|i^men|tal', 3, 2),
('comprehensible', '_com|pre^hen|sible', 3, 2),
('cosmopolitan', '_cos|mo^pol|i|tan', 3, 2),
('identify', '_i^den|ti_fy', 2, 3),
('intensify', '|in^ten|si_fy', 2, 2),
('intoxicate', '|in^tox|i_cate', 2, 2),
('accumulate', '|ac^cu|mu_late', 2, 2),
('commercialise', '|com^mer|cia_lise', 2, 2),
('apologise', '|a^pol|o_gise', 2, 2),
('clarify', '^clar|i_fy', 2, 2),
('criticise', '^crit|i_cize', 2, 2),
('congratulate', '|con^grat|u_late', 2, 2),
('purify', '^pu|ri_fy', 2, 2),
('verify', '^ver|i_fy', 2, 2),
('globalise', '^glo|ba_lise', 2, 2),
('terrify', '^terr|i_fy', 2, 2),
('organise', '^or|ga_nise', 2, 2),
('decorate', '^dec|o_rate', 2, 2),
('emulate', '^em|u_late', 2, 2),
('stimulate', '^stim|u_late', 2, 2),
('crucify', '^cru|ci_fy', 2, 2),
('capitalise', '^cap|i|ta_lise', 2, 2),
('personalise', '^per|so|na_lise', 2, 2),
('vocalise', '^vo|ca_lise', 2, 2),
('negotiate', '|ne^go|ti_ate', 2, 2),
('communicate', '|co^mmu|ni_cate', 2, 2),
('imitate', '^im|i_tate', 2, 2),
('satisfy', '^sat|is_fy', 2, 2),
('justify', '^jus|ti_fy', 2, 2),
('realise', '^rea_lise', 2, 2),
('discriminate', '|dis^crim|i_nate', 2, 2),
('classify', '^class|i_fy', 2, 2),
('operate', '^op|e_rate', 2, 2),
('appreciate', '|ap^pre|ci_ate', 2, 2),
('exaggerate', '|e^xagg|e_rate', 2, 2),
('recognise', '^rec|og_nise', 2, 2),
('electrify', '|e^lec|tri_fy', 2, 2),
('certify', '^cer|ti_fy', 2, 2),
('memorise', '^mem|o_rise', 2, 2),
('qualify', '^qual|i_fy', 2, 2),
('publicise', '^pub|li_cise', 2, 2);